In [1]:
from pathlib import Path
import pandas as pd 
import tarfile
import urllib.request

In [2]:
def load_housing_data():
  tarball_path=Path("datasets/housing.tgz")
  if not tarball_path.is_file():
    Path("datasets").mkdir(parents=True, exist_ok=True)
    url='https://github.com/ageron/data/raw/main/housing.tgz'
    urllib.request.urlretrieve(url,tarball_path)
    with tarfile.open(tarball_path) as housing_tarball:
      housing_tarball.extractall(path='datasets')
  return pd.read_csv(Path("datasets/housing/housing.csv"))

In [3]:
housing_data=load_housing_data()

In [4]:
housing_data.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

In [5]:
housing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [6]:
housing_data['rooms_per_house']=housing_data['total_rooms']/housing_data['households']
housing_data['bedrooms_ratio']=housing_data['total_bedrooms']/housing_data['total_rooms']
housing_data['people_per_house']=housing_data['population']/housing_data['households']

In [7]:
corr_matrix=housing_data.corr(numeric_only=True)
corr_matrix['median_house_value'].sort_values(ascending=False)

median_house_value    1.000000
median_income         0.688075
rooms_per_house       0.151948
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049686
people_per_house     -0.023737
population           -0.024650
longitude            -0.045967
latitude             -0.144160
bedrooms_ratio       -0.255880
Name: median_house_value, dtype: float64

### Seprating features into predictors and target 

In [8]:
housing_predictors=housing_data.drop('median_house_value',axis=1)
housing_labels=housing_data['median_house_value'].copy

In [9]:
housing_predictors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   ocean_proximity     20640 non-null  object 
 9   rooms_per_house     20640 non-null  float64
 10  bedrooms_ratio      20433 non-null  float64
 11  people_per_house    20640 non-null  float64
dtypes: float64(11), object(1)
memory usage: 1.9+ MB


In [10]:
import numpy as np

In [11]:
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(strategy='median')


In [12]:
housing_num=housing_predictors.select_dtypes(include=[np.number])
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [13]:
imputer.statistics_

array([-1.18490000e+02,  3.42600000e+01,  2.90000000e+01,  2.12700000e+03,
        4.35000000e+02,  1.16600000e+03,  4.09000000e+02,  3.53480000e+00,
        5.22912879e+00,  2.03162434e-01,  2.81811565e+00])

In [14]:
x=imputer.transform(housing_num)

In [15]:
housing_tr=pd.DataFrame(x,columns=housing_num.columns,index=housing_num.index)

In [16]:
housing_tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   rooms_per_house     20640 non-null  float64
 9   bedrooms_ratio      20640 non-null  float64
 10  people_per_house    20640 non-null  float64
dtypes: float64(11)
memory usage: 1.7 MB


In [17]:
housing_cat=housing_data[['ocean_proximity']]

In [18]:
from sklearn.preprocessing import OrdinalEncoder
ordien=OrdinalEncoder()

housing_cat_encoded=ordien.fit_transform(housing_cat)

In [19]:
housing_cat_encoded

array([[3.],
       [3.],
       [3.],
       ...,
       [1.],
       [1.],
       [1.]])

In [20]:
#numeric and categarical attributes needed to be combined
housing_tr
housing_cat_encoded

array([[3.],
       [3.],
       [3.],
       ...,
       [1.],
       [1.],
       [1.]])

In [21]:
housing_tr.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  rooms_per_house  bedrooms_ratio  \
0       322.0       126.0         8.3252         6.984127        0.146591   
1      2401.0      1138.0         8.3014         6.238137        0.155797   
2       496.0       177.0         7.2574         8.288136        0.129516   

   people_per_house  
0          2.555556  
1          2.109842  
2          2.802260

In [22]:
housing_cat_encoded

array([[3.],
       [3.],
       [3.],
       ...,
       [1.],
       [1.],
       [1.]])